using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "Category Data", menuName = "Guess the Word/New Category Data")]
public class CategoryData : ScriptableObject
{
    public string categoryName;
    public List<string> wordList = new List<string>();

    [TextArea(2,5)]
    public string description;


    public void SetupWord(int index)
    {
        switch (index)
        {
            case 0:
                AddWordUntar();
                break;
            case 1:
                AddWordSinger();
                break;
            case 2:
                AddWordAnime();
                break;
            case 3:
                AddWordGame();
                break;
            case 4:
                AddWordMusic();
                break;
            default:
                Debug.Log("Not yet implemented");
                break;
        }
    }

    private void AddWordUntar()
    {
        wordList.Add("Fakultas Teknologi Informasi");
        wordList.Add("Fakultas Ekonomi dan Bisnis");
        wordList.Add("Fakultas Hukum");
        wordList.Add("Fakultas Teknik");
        wordList.Add("Fakultas Psikologi");
        wordList.Add("Fakultas Kedokteran");
        wordList.Add("Fakultas Seni Rupa dan Desain");
        wordList.Add("Fakultas Ilmu Komunikasi");
        wordList.Add("Akuntansi Bisnis");
        wordList.Add("Manajemen Bisnis");
        wordList.Add("Arsitektur");
        wordList.Add("Teknik Sipil");
        wordList.Add("Teknik Mesin");
        wordList.Add("Teknik Elektro");
        wordList.Add("Teknik Industri");
        wordList.Add("Teknik Informatika");
        wordList.Add("Sistem Informasi");
        wordList.Add("Desain Interior");
        wordList.Add("Desain Komunikasi Visual");
        wordList.Add("Ilmu Komunikasi");
        wordList.Add("Darius Andana Haris");
        wordList.Add("Gedung R");
        wordList.Add("Gedung M");
        wordList.Add("Gedung Parkiran");
        wordList.Add("GOR");
        wordList.Add("Kantin");
        wordList.Add("Gedung 1");
        wordList.Add("Gedung 2");
        wordList.Add("Lift");
        wordList.Add("T-Space");
        wordList.Add("Laboratorium");
        wordList.Add("Ruang Kelas");
        wordList.Add("Mahasiswa");
        wordList.Add("Dosen");
        wordList.Add("Perpustakaan");
        wordList.Add("Game Development");
        wordList.Add("MBKM");
        wordList.Add("Mahasiswa Baru");
        wordList.Add("Senior");
        wordList.Add("Junior");
        wordList.Add("Asisten Dosen");
        wordList.Add("Alumni");
        wordList.Add("Lintar");
        wordList.Add("Tagihan BPP");
        wordList.Add("Tagihan SKS");
        wordList.Add("Pengenalan Mahasiswa Baru");
        wordList.Add("Unit Kegiatan Mahasiswa");
        wordList.Add("Badan Eksekutif Mahasiswa");
        wordList.Add("Dewan Perwakilan Mahasiswa");
        wordList.Add("Teknik Elektro");
        wordList.Add("Ruang Dosen");
    }

    private void AddWordSinger()
    {
        Debug.Log("Add Word Artist");

        wordList.Add("The Beatles");
        wordList.Add("Michael Jackson");
        wordList.Add("Elvis Presley");
        wordList.Add("Madonna");
        wordList.Add("MLTR - Michael Learn to Rock");
        wordList.Add("Queen");
        wordList.Add("Led Zeppelin");
        wordList.Add("Whitney Houston");
        wordList.Add("Eminem");
        wordList.Add("Taylor Swift");
        wordList.Add("Beyoncé");
        wordList.Add("Neck Deep");
        wordList.Add("Ariana Grande");
        wordList.Add("Rihanna");
        wordList.Add("Drake");
        wordList.Add("The Rolling Stones");
        wordList.Add("Kanye West");
        wordList.Add("Lady Gaga");
        wordList.Add("Adele");
        wordList.Add("U2");
        wordList.Add("Bruce Springsteen");
        wordList.Add("Justin Bieber");
        wordList.Add("The Beach Boys");
        wordList.Add("Maroon 5");
        wordList.Add("The Eagles");
        wordList.Add("Billy Joel");
        wordList.Add("Jay-Z");
        wordList.Add("ABBA");
        wordList.Add("Bruno Mars");
        wordList.Add("Coldplay");
        wordList.Add("Nirvana");
        wordList.Add("Stevie Wonder");
        wordList.Add("Prince");
        wordList.Add("Mariah Carey");
        wordList.Add("The Doors");
        wordList.Add("Pink Floyd");
        wordList.Add("David Bowie");
        wordList.Add("The Who");
        wordList.Add("Linkin Park");
        wordList.Add("Foo Fighters");
        wordList.Add("Green Day");
        wordList.Add("Metallica");
        wordList.Add("Fleetwood Mac");
        wordList.Add("Johnny Cash");
        wordList.Add("Katy Perry");
        wordList.Add("The Weeknd");
        wordList.Add("Post Malone");
        wordList.Add("Shakira");
        wordList.Add("Harry Styles");
        wordList.Add("Sam Smith");

        wordList.Add("Aerosmith");
        wordList.Add("Bon Jovi");
        wordList.Add("Blink-182");
        wordList.Add("R.E.M.");
        wordList.Add("The Police");
        wordList.Add("The Smashing Pumpkins");
        wordList.Add("Creedence Clearwater Revival");
        wordList.Add("Santana");
        wordList.Add("The Clash");
        wordList.Add("Journey");
        wordList.Add("The Cranberries");
        wordList.Add("The Killers");
        wordList.Add("Kings of Leon");
        wordList.Add("The Strokes");
        wordList.Add("Paramore");
        wordList.Add("Alice in Chains");
        wordList.Add("The Velvet Underground");
        wordList.Add("Panic! At The Disco");
        wordList.Add("My Chemical Romance");
        wordList.Add("Simon & Garfunkel");
        wordList.Add("Earth, Wind & Fire");
        wordList.Add("Scorpions");
        wordList.Add("Foreigner");
        wordList.Add("The Kinks");
        wordList.Add("The Cure");
        wordList.Add("The Black Keys");
        wordList.Add("MGMT");
        wordList.Add("No Doubt");
        wordList.Add("The Chainsmokers");
        wordList.Add("Daft Punk");
        wordList.Add("Depeche Mode");
        wordList.Add("Pharrell Williams");
        wordList.Add("The Script");
        wordList.Add("Pentatonix");
        wordList.Add("Toto");
        wordList.Add("Imagine Dragons");
        wordList.Add("The 1975");
        wordList.Add("Foster the People");
        wordList.Add("Hozier");
        wordList.Add("Florence + The Machine");
        wordList.Add("Portugal. The Man");
        wordList.Add("Twenty One Pilots");
        wordList.Add("Mötley Crüe");
        wordList.Add("Def Leppard");
        wordList.Add("The White Stripes");
        wordList.Add("Gorillaz");
        wordList.Add("Arcade Fire");
        wordList.Add("The Lumineers");
        wordList.Add("Radiohead");
        wordList.Add("The Prodigy");
        wordList.Add("The Chainsmokers");
    }

    private void AddWordAnime()
    {
        Debug.Log("Add Word Film");

        wordList.Add("Fullmetal Alchemist: Brotherhood");
        wordList.Add("Attack on Titan");
        wordList.Add("Death Note");
        wordList.Add("Steins;Gate");
        wordList.Add("Your Name");
        wordList.Add("My Hero Academia");
        wordList.Add("One Piece");
        wordList.Add("Naruto");
        wordList.Add("Hunter x Hunter");
        wordList.Add("Demon Slayer: Kimetsu no Yaiba");
        wordList.Add("Code Geass: Lelouch of the Rebellion");
        wordList.Add("Sword Art Online");
        wordList.Add("Neon Genesis Evangelion");
        wordList.Add("Spirited Away");
        wordList.Add("The Disappearance of Haruhi Suzumiya");
        wordList.Add("Clannad: After Story");
        wordList.Add("Dragon Ball Z");
        wordList.Add("Mob Psycho 100");
        wordList.Add("Vinland Saga");
        wordList.Add("Tokyo Ghoul");
        wordList.Add("One Punch Man");
        wordList.Add("Bleach");
        wordList.Add("Re:Zero - Starting Life in Another World");
        wordList.Add("Your Lie in April");
        wordList.Add("Fate/Zero");
        wordList.Add("Kimi no Na wa (Your Name)");
        wordList.Add("Fairy Tail");
        wordList.Add("Monster");
        wordList.Add("Hajime no Ippo");
        wordList.Add("Made in Abyss");
        wordList.Add("No Game No Life");
        wordList.Add("Baccano!");
        wordList.Add("Sword Art Online: Alicization");
        wordList.Add("The Promised Neverland");
        wordList.Add("Hyouka");
        wordList.Add("KonoSuba: God's Blessing on This Wonderful World!");
        wordList.Add("Death Parade");
        wordList.Add("Fate/Stay Night: Unlimited Blade Works");
        wordList.Add("Paranoia Agent");
        wordList.Add("Gintama");
        wordList.Add("Mob Psycho 100 II");
        wordList.Add("That Time I Got Reincarnated as a Slime");
        wordList.Add("Fruits Basket");
        wordList.Add("Akame ga Kill!");
        wordList.Add("The Seven Deadly Sins");
        wordList.Add("Noragami");
        wordList.Add("Soul Eater");
        wordList.Add("Black Clover");
        wordList.Add("Zankyou no Terror");
        wordList.Add("Kabaneri of the Iron Fortress");
        wordList.Add("Elfen Lied");
        wordList.Add("Anohana: The Flower We Saw That Day");
        wordList.Add("Shingeki no Kyojin (Attack on Titan)");
        wordList.Add("Durarara!!");
        wordList.Add("Yuri on Ice");
        wordList.Add("The Ancient Magus' Bride");
        wordList.Add("Toradora!");
        wordList.Add("Tokyo Revengers");
        wordList.Add("Kaguya-sama: Love Is War");
        wordList.Add("Golden Kamuy");
        wordList.Add("The Rising of the Shield Hero");
        wordList.Add("A Silent Voice");
        wordList.Add("Fairy Tail: Final Series");
        wordList.Add("To Your Eternity");
        wordList.Add("Kono Oto Tomare! Sounds of Life");
        wordList.Add("Bakemonogatari");
        wordList.Add("Dorohedoro");
        wordList.Add("Little Witch Academia");
        wordList.Add("Kiseijuu: Sei no Kakuritsu");
        wordList.Add("The Devil is a Part-Timer!");
        wordList.Add("Inuyasha");
        wordList.Add("Bakemonogatari");
        wordList.Add("Nagi no Asukara");
        wordList.Add("Re:Creators");
        wordList.Add("Kino's Journey");
        wordList.Add("Violet Evergarden");
        wordList.Add("The Saga of Tanya the Evil");
        wordList.Add("Guilty Crown");
        wordList.Add("Plastic Memories");
        wordList.Add("Angel Beats!");
        wordList.Add("Rascal Does Not Dream of Bunny Girl Senpai");
        wordList.Add("Wotakoi: Love is Hard for Otaku");
        wordList.Add("Danganronpa: The Animation");
        wordList.Add("Black Bullet");
        wordList.Add("Kyoukai no Kanata");
        wordList.Add("Bunny Girl Senpai");
        wordList.Add("Shouwa Genroku Rakugo Shinjuu");
        wordList.Add("Kyoukai no Rinne");
        wordList.Add("KonoSuba: God's Blessing on This Wonderful World! Legend of Crimson");
        wordList.Add("The Asterisk War");
        wordList.Add("Chihayafuru");
        wordList.Add("Sekirei");
        wordList.Add("Fate/kaleid liner Prisma☆Illya");
        wordList.Add("Kono Oto Tomare! Sounds of Life");
        wordList.Add("Tsubasa: Reservoir Chronicle");
        wordList.Add("Hellsing Ultimate");
        wordList.Add("Shiki");
        wordList.Add("Berserk");
        wordList.Add("The Tatami Galaxy");
        wordList.Add("Steins;Gate 0");
        wordList.Add("Toradora!");
        wordList.Add("Zetsuen no Tempest");
        wordList.Add("Bungou Stray Dogs");
        wordList.Add("Kaguya-sama: Love Is War - Ultra Romantic");
        wordList.Add("Sword Art Online: Gun Gale Online");
        wordList.Add("Gundam Wing");
        wordList.Add("Guilty Crown");
        wordList.Add("Grimgar: Ashes and Illusions");
        wordList.Add("K Project");
        wordList.Add("Monster Musume: Everyday Life with Monster Girls");
        wordList.Add("My Dress-Up Darling");
        wordList.Add("Shoujo Shuumatsu Ryokou");
        wordList.Add("Jujutsu Kaisen");
        wordList.Add("Parasyte: The Maxim");
        wordList.Add("Kimi to Boku");
        wordList.Add("Kimi no Na wa (Your Name)");
        wordList.Add("The World God Only Knows");
        wordList.Add("Ouran High School Host Club");
        wordList.Add("Mushoku Tensei: Jobless Reincarnation");
        wordList.Add("Takt Op. Destiny");
        wordList.Add("Zetsuen no Tempest");
        wordList.Add("Toradora!");
        wordList.Add("Chouyuu Sekai: Being a Hero is Too Hard");
        wordList.Add("Kaguya-sama: Love is War");
        wordList.Add("Sword Art Online: Progressive");
        wordList.Add("High School DxD");
        wordList.Add("Hellsing");
        wordList.Add("Alderamin on the Sky");
        wordList.Add("Nisekoi: False Love");
        wordList.Add("Sankarea: Undying Love");
        wordList.Add("The Case Study of Vanitas");
        wordList.Add("Shiki");
        wordList.Add("The World God Only Knows");
        wordList.Add("Kaguya-sama: Love Is War");
        wordList.Add("Zetsuen no Tempest");
        wordList.Add("Mushoku Tensei: Jobless Reincarnation");
        wordList.Add("Alderamin on the Sky");
        wordList.Add("Nisekoi: False Love");

    }

    private void AddWordGame()
    {
        Debug.Log("Add Word Game");

        wordList.Add("Animal Crossing: New Horizons");
        wordList.Add("Among Us");
        wordList.Add("Apex Legends");
        wordList.Add("Assassin's Creed Valhalla");
        wordList.Add("Battlefield 2042");
        wordList.Add("Bloodborne");
        wordList.Add("Call of Duty: Modern Warfare");
        wordList.Add("Civilization V");
        wordList.Add("Counter-Strike: Source");
        wordList.Add("Cyberpunk 2077");
        wordList.Add("Dark Souls II");
        wordList.Add("Destiny 2: Forsaken");
        wordList.Add("Diablo II: Resurrected");
        wordList.Add("Doom (2016)");
        wordList.Add("Dota Underlords");
        wordList.Add("Elden Ring");
        wordList.Add("Fall Guys: Ultimate Knockout");
        wordList.Add("Far Cry 6");
        wordList.Add("Final Fantasy VII Remake");
        wordList.Add("Fortnite: Save the World");
        wordList.Add("Ghost of Tsushima: Director's Cut");
        wordList.Add("God of War Ragnarök");
        wordList.Add("Grand Theft Auto Online");
        wordList.Add("Hades");
        wordList.Add("Halo: The Master Chief Collection");
        wordList.Add("Hollow Knight: Silksong");
        wordList.Add("Horizon Forbidden West");
        wordList.Add("League of Legends: Wild Rift");
        wordList.Add("Mario Kart Wii");
        wordList.Add("Marvel's Spider-Man: Miles Morales");
        wordList.Add("Mass Effect 2");
        wordList.Add("Minecraft Dungeons");
        wordList.Add("Monster Hunter Rise");
        wordList.Add("Overwatch 2");
        wordList.Add("PUBG Mobile");
        wordList.Add("Persona 5 Strikers");
        wordList.Add("Persona 3 FES");
        wordList.Add("Red Dead Redemption");
        wordList.Add("Resident Evil 3 Remake");
        wordList.Add("Sekiro: Shadows Die Twice");
        wordList.Add("Stardew Valley: Expanded");
        wordList.Add("Street Fighter IV");
        wordList.Add("Super Mario 3D World + Bowser's Fury");
        wordList.Add("The Legend of Zelda: Skyward Sword HD");
        wordList.Add("The Sims 4: Seasons");
        wordList.Add("The Witcher 2: Assassins of Kings");
        wordList.Add("Uncharted: The Lost Legacy");
        wordList.Add("Valorant");
        wordList.Add("World of Warcraft: Shadowlands");
        wordList.Add("Yakuza: Like a Dragon");
        wordList.Add("Half-Life: Alyx");
        wordList.Add("Genshin Impact");
        wordList.Add("Nioh 2");
        wordList.Add("CyberConnect2");
        wordList.Add("Final Fantasy X/X-2 HD Remaster");
        wordList.Add("Kingdom Hearts III");
        wordList.Add("Shadow of the Tomb Raider");
        wordList.Add("Ratchet & Clank: Rift Apart");
        wordList.Add("Guitar Hero III: Legends of Rock");
        wordList.Add("Forza Horizon 4");
        wordList.Add("Gran Turismo 7");
        wordList.Add("Cities: Skylines");
        wordList.Add("Dying Light 2 Stay Human");
        wordList.Add("The Elder Scrolls V: Skyrim Special Edition");
        wordList.Add("Splatoon 2");
        wordList.Add("Star Wars Jedi: Fallen Order");
        wordList.Add("Control");
        wordList.Add("Ghostrunner");
        wordList.Add("Death Stranding");
        wordList.Add("The Last of Us Part II");
        wordList.Add("Cyberpunk 2077: Phantom Liberty");
        wordList.Add("Monster Hunter: Stories 2");
        wordList.Add("Assassin's Creed Odyssey");
        wordList.Add("Resident Evil Village");
        wordList.Add("Street Fighter VI");
        wordList.Add("Final Fantasy XIV: Endwalker");
        wordList.Add("Octopath Traveler");
        wordList.Add("Dragon Quest XI: Echoes of an Elusive Age");
        wordList.Add("Fire Emblem: Three Houses");
        wordList.Add("Persona 4 Golden");
        wordList.Add("Granblue Fantasy Versus");
        wordList.Add("The Binding of Isaac: Rebirth");
        wordList.Add("Nexomon: Extinction");
        wordList.Add("Stardew Valley: 1.5 Update");
        wordList.Add("Etrian Mystery Dungeon");
        wordList.Add("Ace Attorney: Phoenix Wright Trilogy");
        wordList.Add("Yonder: The Cloud Catcher Chronicles");
        wordList.Add("Watch Dogs: Legion");
        wordList.Add("Outer Wilds");
        wordList.Add("Xenoblade Chronicles 2");
        wordList.Add("Monster Hunter Generations Ultimate");
        wordList.Add("Ni no Kuni II: Revenant Kingdom");
        wordList.Add("Danganronpa: Trigger Happy Havoc");
        wordList.Add("Little Nightmares II");
        wordList.Add("A Plague Tale: Innocence");
        wordList.Add("Sonic Mania");
        wordList.Add("Cuphead");
        wordList.Add("Baldur's Gate III");
        wordList.Add("FIFA 22");
        wordList.Add("Madden NFL 22");
        wordList.Add("NHL 22");
        wordList.Add("WWE 2K Battlegrounds");
        wordList.Add("Tony Hawk's Pro Skater 1 + 2");
        wordList.Add("ARK: Survival Evolved");
        wordList.Add("Valheim");
        wordList.Add("Terraria");
        wordList.Add("Dead Cells");
        wordList.Add("Hollow Knight: Silksong");
        wordList.Add("Fallout 4");
        wordList.Add("No Man's Sky");
        wordList.Add("The Outer Worlds");
        wordList.Add("Starbound");
        wordList.Add("Dragon Age: Inquisition");
        wordList.Add("Mass Effect 3");
        wordList.Add("Horizon: Zero Dawn - Complete Edition");
        wordList.Add("Path of Exile");
        wordList.Add("Monster Train");
        wordList.Add("Slay the Spire");
        wordList.Add("The Last Guardian");
        wordList.Add("SoulCalibur VI");
        wordList.Add("Overcooked! 2");
        wordList.Add("Rocket League");
        wordList.Add("Minecraft: Story Mode");
        wordList.Add("Skullgirls");
        wordList.Add("Divinity: Original Sin II");
        wordList.Add("Dying Light");
        wordList.Add("Portal 2");
        wordList.Add("Titanfall 2");
        wordList.Add("Battlefield 1");
        wordList.Add("The Witcher: Enhanced Edition");
        wordList.Add("Ghost Recon Breakpoint");
        wordList.Add("Rainbow Six Siege");
        wordList.Add("Age of Empires IV");
        wordList.Add("Total War: Warhammer III");
        wordList.Add("Civilization VI: Gathering Storm");
        wordList.Add("Spelunky 2");
        wordList.Add("Valhalla: Cyberpunk Bartender Action");
        wordList.Add("Hades: Eternal Edition");
    }

    private void AddWordMusic()
    {
        Debug.Log("Add Word Music");

        wordList.Add("Bohemian Rhapsody");
        wordList.Add("Billie Jean");
        wordList.Add("Shape of You");
        wordList.Add("Rolling in the Deep");
        wordList.Add("Hotel California");
        wordList.Add("Like a Rolling Stone");
        wordList.Add("Stairway to Heaven");
        wordList.Add("Hey Jude");
        wordList.Add("Wonderwall");
        wordList.Add("I Will Always Love You");
        wordList.Add("Smells Like Teen Spirit");
        wordList.Add("Back in Black");
        wordList.Add("Uptown Funk");
        wordList.Add("Sweet Child o' Mine");
        wordList.Add("Shake It Off");
        wordList.Add("Someone Like You");
        wordList.Add("Lose Yourself");
        wordList.Add("Hallelujah");
        wordList.Add("Dancing Queen");
        wordList.Add("Girls Just Want to Have Fun");
        wordList.Add("My Heart Will Go On");
        wordList.Add("Born to Run");
        wordList.Add("All of Me");
        wordList.Add("Call Me Maybe");
        wordList.Add("Thinking Out Loud");
        wordList.Add("Let It Be");
        wordList.Add("Wonderwall");
        wordList.Add("Despacito");
        wordList.Add("Take On Me");
        wordList.Add("Fight Song");
        wordList.Add("Bleeding Love");
        wordList.Add("We Are the Champions");
        wordList.Add("Rolling in the Deep");
        wordList.Add("Sorry");
        wordList.Add("Chasing Cars");
        wordList.Add("Toxic");
        wordList.Add("Killing Me Softly");
        wordList.Add("Under Pressure");
        wordList.Add("Blackbird");
        wordList.Add("Shake It Off");
        wordList.Add("Dance Monkey");
        wordList.Add("Despacito");
        wordList.Add("Stay with Me");
        wordList.Add("Let It Go");
        wordList.Add("I Want to Hold Your Hand");
        wordList.Add("What a Wonderful World");
        wordList.Add("Livin' on a Prayer");
        wordList.Add("Don't Stop Believin'");
        wordList.Add("Good Vibrations");
        wordList.Add("I Gotta Feeling");
        wordList.Add("Bad Romance");
        wordList.Add("Crazy in Love");

        wordList.Add("Yesterday");
        wordList.Add("Let It Go");
        wordList.Add("Halo");
        wordList.Add("Single Ladies (Put a Ring on It)");
        wordList.Add("Sorry");
        wordList.Add("Shake It Off");
        wordList.Add("Wonderwall");
        wordList.Add("Rolling in the Deep");
        wordList.Add("Someone Like You");
        wordList.Add("Sweet Caroline");
        wordList.Add("Take Me Home, Country Roads");
        wordList.Add("I Will Survive");
        wordList.Add("Born This Way");
        wordList.Add("Hey Ya!");
        wordList.Add("Time After Time");
        wordList.Add("A Thousand Years");
        wordList.Add("Zombie");
        wordList.Add("Poker Face");
        wordList.Add("Empire State of Mind");
        wordList.Add("Watermelon Sugar");
        wordList.Add("If I Ain't Got You");
        wordList.Add("Rolling in the Deep");
        wordList.Add("Uptown Funk");
        wordList.Add("Billie Eilish");
        wordList.Add("We Belong Together");
        wordList.Add("Hotline Bling");
        wordList.Add("I Don't Want to Miss a Thing");
        wordList.Add("Complicated");
        wordList.Add("Don't Speak");
        wordList.Add("Clandestino");
        wordList.Add("Hey Jude");
        wordList.Add("Roxanne");
        wordList.Add("Dancing in the Dark");
        wordList.Add("Take a Bow");
        wordList.Add("Back to December");
        wordList.Add("Bad Guy");
        wordList.Add("Closer");
        wordList.Add("Titanium");
        wordList.Add("Electricity");
        wordList.Add("My Immortal");
        wordList.Add("Runaway");
        wordList.Add("Kiss from a Rose");
        wordList.Add("Hurt");
        wordList.Add("Perfect");
        wordList.Add("Viva La Vida");
        wordList.Add("Karma Chameleon");
        wordList.Add("Born to Run");
        wordList.Add("Isn’t She Lovely");
        wordList.Add("Jessie's Girl");
        wordList.Add("Black Magic Woman");
        wordList.Add("Stand by Me");
        wordList.Add("All About That Bass");
        wordList.Add("Take It Easy");
        wordList.Add("Here Comes the Sun");
        wordList.Add("More Than a Feeling");
        wordList.Add("Dance with My Father");
        wordList.Add("Don't Let Me Down");
        wordList.Add("I Want to Break Free");
        wordList.Add("Tears in Heaven");
        wordList.Add("Good Riddance (Time of Your Life)");
        wordList.Add("Somebody to Love");
        wordList.Add("Crazy");
        wordList.Add("Mr. Brightside");
        wordList.Add("Can't Stop the Feeling!");
        wordList.Add("I’ll Be There for You");
        wordList.Add("Boulevard of Broken Dreams");
        wordList.Add("I Want it That Way");
        wordList.Add("How Deep Is Your Love");
        wordList.Add("The Way You Make Me Feel");
        wordList.Add("Material Girl");
        wordList.Add("Sweet Dreams (Are Made of This)");
        wordList.Add("Lady Marmalade");
        wordList.Add("I Will Always Love You");
        wordList.Add("Finesse");
        wordList.Add("Ain't No Mountain High Enough");
        wordList.Add("Billie Jean");
        wordList.Add("You Are Not Alone");
        wordList.Add("I’ll Be Missing You");
        wordList.Add("Let’s Get It On");
        wordList.Add("Bizarre Love Triangle");
        wordList.Add("All of Me");
        wordList.Add("Love Yourself");
        wordList.Add("Party in the USA");
        wordList.Add("The Way I Are");
        wordList.Add("Everybody Wants to Rule the World");
        wordList.Add("One More Night");
        wordList.Add("What Makes You Beautiful");
        wordList.Add("It's Raining Men");
        wordList.Add("Dancing on My Own");
        wordList.Add("Rolling in the Deep");
        wordList.Add("Bad Romance");
        wordList.Add("Since U Been Gone");
        wordList.Add("American Pie");
        wordList.Add("Somebody That I Used to Know");
        wordList.Add("Last Christmas");
        wordList.Add("We Are Family");
        wordList.Add("Say My Name");
        wordList.Add("I Can’t Help Falling in Love");
        wordList.Add("Dream On");
        wordList.Add("Let’s Hear It for the Boy");
        wordList.Add("Sweet Child o' Mine");
    }




}
